### ISSUE TITLE
无法打卡

### ISSUE THREAD

**Issue by moqiank** [GCS-ZHN/AutoCard-Android#1]
提示返回浙江省有问题，无法打卡

**Comment by GCS-ZHN** [comment]
应该是因为我好久没更新安卓版了，autoCard项目是正常的



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
发件人: moqiank ***@***.***&gt;
发送时间: 2022年3月29日 09:38
收件人: GCS-ZHN/AutoCard-Android ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [GCS-ZHN/AutoCard-Android] 无法打卡 (Issue #1)





 
提示返回浙江省有问题，无法打卡

**Comment by GCS-ZHN** [comment]
晚些我把安卓版的更新一下，建议先使用AutoCard普通版

**Comment by GCS-ZHN** [comment]
安卓版打卡功能代码较为老旧，建议使用 [AutoCard](https://github.com/GCS-ZHN/AutoCard)
